// @axis-love/core — sanitization schema and URL policy
//
// Security policy owned by core. The sanitize schema extends
// rehype-sanitize defaults to allow safe inline HTML tags, GitHub alerts,
// KaTeX MathML, Mermaid SVG, and code highlighting styles.
//
// The URL policy plugin enforces scheme allow-listing, strips event handlers,
// blocks path traversal, removes elements with unsafe URLs entirely, and
// adds rel="noopener noreferrer" to external links.
//
// These are internal implementation details — not re-exported.

import type { Element, Root as HastRoot, Properties } from "hast";
import { defaultSchema, type Schema } from "hast-util-sanitize";
import type { Plugin } from "unified";
import { SKIP, visit } from "unist-util-visit";

// ---------------------------------------------------------------------------
// Custom sanitize schema (extends rehype-sanitize defaults)
// ---------------------------------------------------------------------------

type Attributes = NonNullable<Schema["attributes"]>;

const defaultAttributes = defaultSchema.attributes as Attributes;

export const sanitizeSchema: Schema = {
  ...defaultSchema,
  clobberPrefix: "",
  tagNames: [
    ...(defaultSchema.tagNames as string[]),
    // Safe inline HTML tags from security policy
    "kbd",
    "mark",
    "sub",
    "sup",
    "abbr",
    "details",
    "summary",
    // GitHub alerts: div wrappers with class
    "div",
    // KaTeX MathML elements
    "math",
    "semantics",
    "mrow",
    "mi",
    "mo",
    "mn",
    "msup",
    "msubsup",
    "annotation",
    "mop",
    "mtext",
    "mfrac",
    "msqrt",
    "mroot",
    "mfenced",
    "mtable",
    "mtr",
    "mtd",
    "munderover",
    "munder",
    "mover",
    "mpadded",
    "mspace",
    "menclose",
    "mglyph",
    "mlabeledtr",
    "mmultiscripts",
    "msub",
    "msup",
    "munderover",
    // NOTE: SVG tags are intentionally NOT allowed in the core sanitize schema.
    // Inline SVG from raw HTML is a security risk (script injection, external
    // references). SVG for Mermaid diagrams is generated by the browser layer
    // after core rendering, not through the unified pipeline.
  ],
  attributes: {
    ...defaultSchema.attributes,
    a: [...(defaultAttributes.a ?? []), "rel", "target"],
    div: [...(defaultAttributes.div ?? []), "className", "dataMermaidSource"],
    p: [...(defaultAttributes.p ?? []), "className"],
    span: [...(defaultAttributes.span ?? []), "className", "style"],
    pre: [...(defaultAttributes.pre ?? []), "className", "dataLanguage", "tabindex", "style"],
    code: [...(defaultAttributes.code ?? []), "className"],
    "*": [...(defaultAttributes["*"] ?? []).filter((attr) => attr !== "name"), "className"],
    math: ["xmlns", "display"],
    annotation: ["encoding"],
  },
};

// ---------------------------------------------------------------------------
// URL scheme policy
// ---------------------------------------------------------------------------

const DEFAULT_ALLOWED_SCHEMES = new Set(["http", "https", "mailto", "tel"]);

const EVENT_ATTR_RE = /^on/i;

const LINK_ELEMENTS = new Set(["a"]);
const SRC_ELEMENTS = new Set(["img", "video", "audio", "source", "track", "embed", "iframe"]);

function isEventHandler(attrName: string): boolean {
  return EVENT_ATTR_RE.test(attrName);
}

// ---------------------------------------------------------------------------
// Path traversal detection
// ---------------------------------------------------------------------------

function decodeUrlOnce(url: string): string {
  try {
    return decodeURIComponent(url);
  } catch {
    return url;
  }
}

function decodeUrlTwice(url: string): string {
  return decodeUrlOnce(decodeUrlOnce(url));
}

function isPathTraversal(url: string): boolean {
  const trimmed = url.trim();

  if (trimmed.includes("%00") || trimmed.includes("\0")) {
    return true;
  }

  if (trimmed.startsWith("\\\\")) {
    return true;
  }

  const variants = [trimmed, decodeUrlOnce(trimmed), decodeUrlTwice(trimmed)];

  for (const v of variants) {
    if (v.includes("../") || v.includes("..\\")) {
      return true;
    }
    if (v.includes("..%2f") || v.includes("..%5c")) {
      return true;
    }
  }

  return false;
}

export function isSafeUrl(url: string, allowedSchemes?: ReadonlySet<string>): boolean {
  const schemes = allowedSchemes ?? DEFAULT_ALLOWED_SCHEMES;
  const trimmed = url.trim();

  if (trimmed === "" || trimmed.startsWith("#")) return true;

  if (isPathTraversal(trimmed)) return false;

  if (/^[./]/.test(trimmed) || !/:/.test(trimmed)) return true;

  const colonIdx = trimmed.indexOf(":");
  if (colonIdx === -1) return true;

  const scheme = trimmed.slice(0, colonIdx).toLowerCase();
  return schemes.has(scheme);
}

// ---------------------------------------------------------------------------
// Link classification
// ---------------------------------------------------------------------------

export function isExternalUrl(url: string, allowedSchemes?: ReadonlySet<string>): boolean {
  const schemes = allowedSchemes ?? DEFAULT_ALLOWED_SCHEMES;
  const trimmed = url.trim();
  if (
    trimmed.startsWith("#") ||
    trimmed.startsWith("/") ||
    trimmed.startsWith("./") ||
    trimmed.startsWith("../")
  ) {
    return false;
  }
  const colonIdx = trimmed.indexOf(":");
  if (colonIdx === -1) return false;
  const scheme = trimmed.slice(0, colonIdx).toLowerCase();
  if (scheme === "mailto" || scheme === "tel") return false;
  return schemes.has(scheme);
}

// ---------------------------------------------------------------------------
// rehype plugin: URL policy with diagnostics
// ---------------------------------------------------------------------------

/**
 * Create a rehype URL policy plugin that:
 * - Removes elements with unsafe URLs (links and media)
 * - Strips event-handler attributes
 * - Adds rel="noopener noreferrer" to external links
 * - Collects diagnostics for blocked URLs
 *
 * Elements with unsafe URLs are removed entirely (including text content)
 * to prevent dangerous strings from appearing in the rendered HTML.
 */
export function createRehypeUrlPolicy(
  allowedSchemes: ReadonlySet<string>,
  collector: { unsafeUrl: (url: string) => void },
): Plugin<[], HastRoot, HastRoot> {
  return function rehypeUrlPolicy() {
    return (tree: HastRoot): HastRoot => {
      visit(tree, "element", (node: Element, index, parent) => {
        if (!node.properties) return;

        const props = node.properties as Properties;
        const tag = node.tagName;

        // Strip event-handler attributes
        for (const attr of Object.keys(props)) {
          if (isEventHandler(attr)) {
            delete props[attr];
          }
        }

        // Check href on links — remove entire element if unsafe
        if (LINK_ELEMENTS.has(tag) && typeof props.href === "string") {
          if (!isSafeUrl(props.href, allowedSchemes)) {
            collector.unsafeUrl(props.href);
            if (parent && typeof index === "number" && "children" in parent) {
              // Remove the link element entirely — text and all
              parent.children.splice(index, 1);
              return SKIP;
            }
          } else if (isExternalUrl(props.href, allowedSchemes)) {
            const existing = Array.isArray(props.rel) ? props.rel : [];
            const tokens = new Set(existing.filter(Boolean));
            tokens.add("noopener");
            tokens.add("noreferrer");
            props.rel = [...tokens];
            if (props.target === undefined) {
              props.target = "_blank";
            }
          }
        }

        // Check src on media/embed elements — remove entire element if unsafe
        if (SRC_ELEMENTS.has(tag)) {
          for (const urlAttr of ["src", "srcset", "data", "poster"] as const) {
            const val = props[urlAttr];
            if (typeof val === "string" && !isSafeUrl(val, allowedSchemes)) {
              collector.unsafeUrl(val);
              if (parent && typeof index === "number" && "children" in parent) {
                // Remove the element entirely
                parent.children.splice(index, 1);
                return SKIP;
              }
            }
          }
        }
      });

      return tree;
    };
  };
}
