// @axis-love/core — sanitization schema and URL policy
//
// Security policy owned by core. The sanitize schema extends
// rehype-sanitize defaults to allow safe inline HTML tags, GitHub alerts,
// KaTeX MathML, Mermaid SVG, and code highlighting styles.
//
// The URL policy plugin enforces scheme allow-listing, strips event handlers,
// blocks path traversal, removes elements with unsafe URLs entirely, and
// adds rel="noopener noreferrer" to external links.
//
// These are internal implementation details — not re-exported.

import type { Element, Root as HastRoot, Properties } from "hast";
import { defaultSchema, type Schema } from "hast-util-sanitize";
import type { Plugin } from "unified";
import { SKIP, visit } from "unist-util-visit";

// ---------------------------------------------------------------------------
// Custom sanitize schema (extends rehype-sanitize defaults)
// ---------------------------------------------------------------------------

type Attributes = NonNullable<Schema["attributes"]>;

const defaultAttributes = defaultSchema.attributes as Attributes;

export const sanitizeSchema: Schema = {
  ...defaultSchema,
  clobberPrefix: "user-content-",
  tagNames: [
    ...(defaultSchema.tagNames as string[]),
    // Safe inline HTML tags from security policy
    "kbd",
    "mark",
    "sub",
    "sup",
    "abbr",
    "details",
    "summary",
    // GitHub alerts: div wrappers with class
    "div",
    // KaTeX MathML elements
    "math",
    "semantics",
    "mrow",
    "mi",
    "mo",
    "mn",
    "msup",
    "msubsup",
    "annotation",
    "mop",
    "mtext",
    "mfrac",
    "msqrt",
    "mroot",
    "mfenced",
    "mtable",
    "mtr",
    "mtd",
    "munderover",
    "munder",
    "mover",
    "mpadded",
    "mspace",
    "menclose",
    "mglyph",
    "mlabeledtr",
    "mmultiscripts",
    "msub",
    "msup",
    "munderover",
    // NOTE: SVG tags are intentionally NOT allowed in the core sanitize schema.
    // Inline SVG from raw HTML is a security risk (script injection, external
    // references). SVG for Mermaid diagrams is generated by the browser layer
    // after core rendering, not through the unified pipeline.
  ],
  attributes: {
    ...defaultSchema.attributes,
    a: [...(defaultAttributes.a ?? []), "rel", "target"],
    div: [...(defaultAttributes.div ?? []), "className", "dataMermaidSource"],
    p: [...(defaultAttributes.p ?? []), "className"],
    span: [...(defaultAttributes.span ?? []), "className", "style"],
    pre: [...(defaultAttributes.pre ?? []), "className", "dataLanguage", "tabindex", "style"],
    code: [...(defaultAttributes.code ?? []), "className"],
    "*": [...(defaultAttributes["*"] ?? []), "className"],
    math: ["xmlns", "display"],
    annotation: ["encoding"],
  },
};

// ---------------------------------------------------------------------------
// URL scheme policy
// ---------------------------------------------------------------------------

const DEFAULT_ALLOWED_SCHEMES = new Set(["http", "https", "mailto", "tel"]);

const EVENT_ATTR_RE = /^on/i;

const LINK_ELEMENTS = new Set(["a"]);
const SRC_ELEMENTS = new Set(["img", "video", "audio", "source", "track", "embed", "iframe"]);

function isEventHandler(attrName: string): boolean {
  return EVENT_ATTR_RE.test(attrName);
}

// ---------------------------------------------------------------------------
// Path traversal detection
// ---------------------------------------------------------------------------

function decodeUrlOnce(url: string): string {
  try {
    return decodeURIComponent(url);
  } catch {
    return url;
  }
}

function decodeUrlTwice(url: string): string {
  return decodeUrlOnce(decodeUrlOnce(url));
}

function isPathTraversal(url: string): boolean {
  const trimmed = url.trim();

  if (trimmed.includes("%00") || trimmed.includes("\0")) {
    return true;
  }

  if (trimmed.startsWith("\\\\")) {
    return true;
  }

  const variants = [trimmed, decodeUrlOnce(trimmed), decodeUrlTwice(trimmed)];

  for (const v of variants) {
    if (v.includes("../") || v.includes("..\\")) {
      return true;
    }
    if (v.includes("..%2f") || v.includes("..%5c")) {
      return true;
    }
  }

  return false;
}

/**
 * Whether a URL is protocol-relative (`//host/path`).
 *
 * Protocol-relative URLs carry no scheme, so scheme checks treat them as
 * relative — but browsers resolve them against the page protocol (http/https)
 * and fetch a REMOTE resource. They must therefore be handled as remote, not
 * local. Control characters are stripped first, mirroring browser URL parsing
 * (e.g. `/\x2f` tricks and leading whitespace/control chars must not bypass).
 */
export function isProtocolRelative(url: string): boolean {
  // biome-ignore lint/suspicious/noControlCharactersInRegex: intentional — control chars are stripped to mirror browser URL parsing before detection
  const stripped = url.trim().replace(/[\x00-\x1F\x7F]/g, "");
  return stripped.startsWith("//");
}

export function isSafeUrl(url: string, allowedSchemes?: ReadonlySet<string>): boolean {
  const schemes = allowedSchemes ?? DEFAULT_ALLOWED_SCHEMES;
  const trimmed = url.trim();

  if (trimmed === "" || trimmed.startsWith("#")) return true;

  // Strip control characters (tab, newline, carriage return, null, etc.)
  // that browsers ignore when parsing URLs. An attacker can insert these
  // to break scheme detection (e.g. "java\tscript:" is treated as
  // "javascript:" by browsers).
  // biome-ignore lint/suspicious/noControlCharactersInRegex: intentional — stripping control chars is the security purpose
  const stripped = trimmed.replace(/[\x00-\x1F\x7F]/g, "");

  if (isPathTraversal(stripped)) return false;

  // Check for scheme: both the raw and percent-decoded forms.
  // A URL like "javascript%3Aalert(1)" has no raw ":" but decodes to
  // "javascript:alert(1)" which is dangerous. Browsers decode %3A → :
  // before scheme resolution.
  const colonIdx = stripped.indexOf(":");
  if (colonIdx !== -1) {
    const scheme = stripped.slice(0, colonIdx).toLowerCase();
    // Reject if there's a scheme that's not in the allow-list.
    // Also reject if the scheme portion contains whitespace or control
    // chars (browsers strip these, e.g. "java\nscript:" → "javascript:").
    // biome-ignore lint/suspicious/noControlCharactersInRegex: intentional — detecting control chars in scheme is the security purpose
    const cleanScheme = scheme.replace(/[\x00-\x20]/g, "");
    if (cleanScheme !== scheme) {
      // Scheme had whitespace/control chars — treat as unsafe
      return false;
    }
    return schemes.has(scheme);
  }

  // No raw colon — check decoded form for an encoded colon (%3A, %253A)
  const decoded = decodeUrlOnce(stripped);
  if (decoded !== stripped) {
    const decodedColon = decoded.indexOf(":");
    if (decodedColon !== -1) {
      const decodedScheme = decoded.slice(0, decodedColon).toLowerCase();
      // Only treat as scheme if it looks like a scheme (alpha chars + digits)
      // Avoid treating "./path" decoded as "./path" with a colon in a query
      // string as a scheme. A valid scheme is [a-zA-Z][a-zA-Z0-9+.-]*
      if (/^[a-z][a-z0-9+.-]*$/i.test(decodedScheme)) {
        return schemes.has(decodedScheme);
      }
    }
    // Double-decode for double-encoded attacks
    const decodedTwice = decodeUrlOnce(decoded);
    if (decodedTwice !== decoded) {
      const decodedTwiceColon = decodedTwice.indexOf(":");
      if (decodedTwiceColon !== -1) {
        const decodedTwiceScheme = decodedTwice.slice(0, decodedTwiceColon).toLowerCase();
        if (/^[a-z][a-z0-9+.-]*$/i.test(decodedTwiceScheme)) {
          return schemes.has(decodedTwiceScheme);
        }
      }
    }
  }

  // Protocol-relative (//host/path) carries no scheme but resolves to a
  // remote http/https resource — it is NOT a local relative path. Treat its
  // scheme as implicitly remote: safe only if a network scheme is allowed.
  // Callers that gate remote access (e.g. remote-image blocking) must
  // additionally consult their own remote policy.
  if (stripped.startsWith("//")) {
    return schemes.has("http") || schemes.has("https");
  }

  // Relative path — safe
  if (/^[./]/.test(stripped) || !/:/.test(stripped)) return true;

  // Should not reach here, but fail closed
  return false;
}

// ---------------------------------------------------------------------------
// Link classification
// ---------------------------------------------------------------------------

export function isExternalUrl(url: string, allowedSchemes?: ReadonlySet<string>): boolean {
  const schemes = allowedSchemes ?? DEFAULT_ALLOWED_SCHEMES;
  const trimmed = url.trim();

  // Protocol-relative (//host/path) resolves to a remote http/https resource,
  // so it is external even though it starts with "/". Check before the local
  // path checks. It is external when a network scheme is permitted.
  if (isProtocolRelative(trimmed)) {
    return schemes.has("http") || schemes.has("https");
  }

  if (
    trimmed.startsWith("#") ||
    trimmed.startsWith("/") ||
    trimmed.startsWith("./") ||
    trimmed.startsWith("../")
  ) {
    return false;
  }
  const colonIdx = trimmed.indexOf(":");
  if (colonIdx === -1) return false;
  const scheme = trimmed.slice(0, colonIdx).toLowerCase();
  if (scheme === "mailto" || scheme === "tel") return false;
  return schemes.has(scheme);
}

// ---------------------------------------------------------------------------
// rehype plugin: URL policy with diagnostics
// ---------------------------------------------------------------------------

/**
 * Create a rehype URL policy plugin that:
 * - Removes elements with unsafe URLs (links and media)
 * - Strips event-handler attributes
 * - Adds rel="noopener noreferrer" to external links
 * - Collects diagnostics for blocked URLs
 *
 * Elements with unsafe URLs are removed entirely (including text content)
 * to prevent dangerous strings from appearing in the rendered HTML.
 */
export function createRehypeUrlPolicy(
  allowedSchemes: ReadonlySet<string>,
  collector: { unsafeUrl: (url: string) => void },
): Plugin<[], HastRoot, HastRoot> {
  return function rehypeUrlPolicy() {
    return (tree: HastRoot): HastRoot => {
      visit(tree, "element", (node: Element, index, parent) => {
        if (!node.properties) return;

        const props = node.properties as Properties;
        const tag = node.tagName;

        // Strip event-handler attributes
        for (const attr of Object.keys(props)) {
          if (isEventHandler(attr)) {
            delete props[attr];
          }
        }

        // Check href on links — remove entire element if unsafe
        if (LINK_ELEMENTS.has(tag) && typeof props.href === "string") {
          if (!isSafeUrl(props.href, allowedSchemes)) {
            collector.unsafeUrl(props.href);
            if (parent && typeof index === "number" && "children" in parent) {
              // Remove the link element entirely — text and all
              parent.children.splice(index, 1);
              return SKIP;
            }
          } else if (isExternalUrl(props.href, allowedSchemes)) {
            const existing = Array.isArray(props.rel) ? props.rel : [];
            const tokens = new Set(existing.filter(Boolean));
            tokens.add("noopener");
            tokens.add("noreferrer");
            props.rel = [...tokens];
            if (props.target === undefined) {
              props.target = "_blank";
            }
          }
        }

        // Check src on media/embed elements — remove entire element if unsafe
        if (SRC_ELEMENTS.has(tag)) {
          for (const urlAttr of ["src", "data", "poster"] as const) {
            const val = props[urlAttr];
            if (typeof val === "string" && !isSafeUrl(val, allowedSchemes)) {
              collector.unsafeUrl(val);
              if (parent && typeof index === "number" && "children" in parent) {
                parent.children.splice(index, 1);
                return SKIP;
              }
            }
          }

          // srcset contains comma-separated URL candidates.
          // Each candidate is "url descriptor" (e.g. "image.png 1x").
          // Check every URL in the srcset.
          const srcset = props.srcset;
          if (typeof srcset === "string") {
            const candidates = srcset.split(",");
            let unsafe = false;
            for (const candidate of candidates) {
              const url = candidate.trim().split(/\s+/)[0];
              if (url && !isSafeUrl(url, allowedSchemes)) {
                collector.unsafeUrl(url);
                unsafe = true;
              }
            }
            if (unsafe && parent && typeof index === "number" && "children" in parent) {
              parent.children.splice(index, 1);
              return SKIP;
            }
          }
        }

        // Check xlink:href on any element (SVG xlink attacks)
        const xlink = props["xlink:href"];
        if (typeof xlink === "string" && !isSafeUrl(xlink, allowedSchemes)) {
          collector.unsafeUrl(xlink);
          // Remove the attribute — the element itself may be safe
          delete props["xlink:href"];
        }
      });

      return tree;
    };
  };
}
