/**
 * Visual baseline test harness — loads pre-rendered HTML fixtures
 * for Playwright screenshot comparison.
 *
 * The fixtures are pre-rendered by `tests/visual/prerender.ts` (run via
 * `npx tsx tests/visual/prerender.ts` or `npm run build:visual`).
 * Pre-rendering is necessary because the built dist artifacts use
 * extensionless internal imports (a known contracts package issue)
 * that Node ESM cannot resolve. The pre-render script uses tsx which
 * handles this correctly.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Fixture definitions — must match the names in prerender.ts.
 */
const VISUAL_FIXTURES = {
  headings:
    "# H1 Heading\n\n## H2 Heading\n\n### H3 Heading\n\n#### H4 Heading\n\n##### H5 Heading\n\n###### H6 Heading",
  tables:
    "| Name | Value | Notes |\n|------|-------|-------|\n| Alpha | 1 | First entry |\n| Beta | 2 | Second entry |\n| Gamma | 3 | Third entry |",
  // biome-ignore lint/suspicious/noTemplateCurlyInString: Markdown fixture contains JS template syntax as text
  code: '```typescript\nconst x: number = 42;\nfunction greet(name: string): string {\n  return `Hello, ${name}!`;\n}\nconsole.log(greet("World"));\n```',
  alerts:
    "> [!NOTE]\n> This is a note with important information.\n\n> [!WARNING]\n> This is a warning about potential issues.\n\n> [!IMPORTANT]\n> This is critical information.",
  mixed:
    "# Document Title\n\n## Introduction\n\nParagraph with **bold** and *italic* text, plus an `inline code` snippet.\n\n```python\ndef fibonacci(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n```\n\n| Column 1 | Column 2 |\n|----------|----------|\n| Cell A | Cell B |\n\n> [!NOTE]\n> A note in the mixed document.\n\n[External link](https://example.com)",
  math: "The equation $E = mc^2$ is famous.\n\nDisplay math:\n\n$$\\int_0^\\infty e^{-x^2} dx = \\frac{\\sqrt{\\pi}}{2}$$\n\nInline math $a^2 + b^2 = c^2$ in a sentence.",
  mermaid:
    "```mermaid\ngraph TD\n    A[Start] --> B{Decision}\n    B -->|Yes| C[Action 1]\n    B -->|No| D[Action 2]\n    C --> E[End]\n    D --> E\n```",
} as const;

export type VisualFixtureName = keyof typeof VISUAL_FIXTURES;
export const FIXTURE_NAMES = Object.keys(VISUAL_FIXTURES) as VisualFixtureName[];

/**
 * Read a pre-rendered fixture HTML file.
 * The file must be generated by `npx tsx tests/visual/prerender.ts`.
 */
export function readFixtureHtml(
  fixtureName: VisualFixtureName,
  theme: "light" | "dark",
  viewport: "desktop" | "narrow",
): string {
  const repoRoot = process.cwd();
  const filename = `${fixtureName}-${theme}-${viewport}.html`;
  return readFileSync(join(repoRoot, "tests", "visual", "fixtures", filename), "utf-8");
}
