/**
 * Visual baseline tests — deterministic screenshot comparisons across
 * browser engines, viewport widths, and theme modes.
 *
 * These tests load pre-rendered HTML fixtures (generated by
 * `npx tsx tests/visual/prerender.ts`) and capture screenshots for
 * baseline comparison. The pre-rendered HTML contains inlined CSS
 * from @axis-love/styles and rendered HTML from @axis-love/core.
 *
 * Browser matrix: Chromium, Firefox, WebKit (from playwright.config.ts projects)
 * Viewport matrix: desktop 1280x720, narrow 375x667
 * Theme matrix: light, dark
 * Fixture matrix: headings, tables, code, alerts, mixed, math, mermaid
 *
 * Prerequisites:
 *   npm run build         — build dist artifacts
 *   npx tsx tests/visual/prerender.ts  — generate fixture HTML files
 *   npx playwright install  — install browser binaries
 *
 * Baseline update rules — see tests/visual/README.md
 */

import { expect, test } from "@playwright/test";
import { FIXTURE_NAMES, readFixtureHtml, type VisualFixtureName } from "./harness";

/**
 * Derive the browser name from the Playwright project name.
 * Project names follow the pattern `{browser}-{viewport}` (e.g.
 * "chromium-desktop", "firefox-narrow").
 */
function getBrowserName(projectName: string): string {
  if (projectName.startsWith("chromium")) return "chromium";
  if (projectName.startsWith("firefox")) return "firefox";
  if (projectName.startsWith("webkit")) return "webkit";
  return projectName;
}

function isNarrowViewport(projectName: string): boolean {
  return projectName.includes("narrow");
}

const THEMES = ["light", "dark"] as const;

for (const fixtureName of FIXTURE_NAMES) {
  for (const theme of THEMES) {
    test.describe(`${fixtureName} — ${theme} theme`, () => {
      test("visual baseline", async ({ page }, testInfo) => {
        const projectName = testInfo.project.name;
        const browser = getBrowserName(projectName);
        const narrow = isNarrowViewport(projectName);
        const viewportLabel = narrow ? "narrow" : "desktop";

        // Load the pre-rendered HTML fixture.
        const html = readFixtureHtml(fixtureName as VisualFixtureName, theme, viewportLabel);
        await page.setContent(html, { waitUntil: "networkidle" });

        // Wait for fonts and layout to settle. The callback runs in
        // browser context — we use a string form to avoid needing DOM
        // types in the test process's tsconfig.
        await page
          .waitForFunction(() => document.fonts.status === "loaded", {
            timeout: 5000,
          })
          .catch(() => {
            // Fonts API not available — proceed (system fonts are synchronous).
          });

        // Small extra wait for any final layout reflow.
        await page.waitForTimeout(100);

        // The screenshot name encodes: fixture, theme, browser, viewport.
        // This ensures each combination has its own baseline. The .png
        // extension is required by Playwright's toHaveScreenshot.
        const screenshotName = `${fixtureName}-${theme}-${browser}-${viewportLabel}.png`;

        // Capture a full-page screenshot. The test page fills the
        // viewport, so this captures the reader as it appears to the user.
        await expect(page).toHaveScreenshot(screenshotName, {
          fullPage: true,
          maxDiffPixelRatio: 0.01,
          threshold: 0.2,
          animations: "disabled",
        });
      });
    });
  }
}
